name: guideh
description: IC GUIDEH LC
publish_to: 'none'

version: 1.2.6+60

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.0.17
  cupertino_icons: ^1.0.2
  intl: 0.19.0
  carousel_slider: ^5.0.0
  yandex_mapkit: ^4.1.0
  url_launcher: ^6.1.10
  permission_handler: ^11.0.0
  flutter_html: ^3.0.0-beta.1
  camera:
  path_provider:
  path:
  flutter_pdfview: ^1.3.1
  go_router: ^14.2.7
  flutter_native_splash: ^2.3.2
  geolocator: ^13.0.1
  mime: ^2.0.0
  flutter_bloc: ^8.1.3
  collection: any
  bloc: any
  flutter_svg: ^2.0.7
  mask_text_input_formatter: ^2.6.0
  flutter_typeahead: ^5.1.0
  web_socket_channel: ^3.0.1
  multi_dropdown: ^3.0.1
  app_links: ^6.3.2
  file_picker: ^8.1.4
  flutter_local_notifications: ^18.0.1
  open_file: ^3.5.10
  flutter_multi_formatter: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash-image.png
  android_12:
    color: "#ffffff"
    image: assets/splash/splash-image-android12.png

  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/checkup_house/
    - assets/images/checkup_kasko/
